### ISSUE TITLE
Installation and running mongo-community as a brew service doesn't work when behind a proxy

### ISSUE THREAD

**Issue by ceyhunsony** [mongodb/homebrew-brew#12]
`brew services start mongodb/brew/mongodb-community@3.2` command yields following output (similar to others which at some point refer to `downloads.mongodb.org` domain):
```
﻿Error: Failed to open TCP connection to downloads.mongodb.org:443 (getaddrinfo: nodename nor servname provided, or not known)
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/net/http.rb:882:in `rescue in block in connect'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/net/http.rb:879:in `block in connect'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/net/http.rb:878:in `connect'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/net/http.rb:852:in `start'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/net/http.rb:584:in `start'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/net/http.rb:479:in `get_response'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/net/http.rb:456:in `get'
/usr/local/Homebrew/Library/Taps/mongodb/homebrew-brew/Formula/mongodb-community@3.2.rb:9:in `<class:MongodbCommunityAT32>'
/usr/local/Homebrew/Library/Taps/mongodb/homebrew-brew/Formula/mongodb-community@3.2.rb:1:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:26:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:26:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:46:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:128:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:273:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:118:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:114:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:263:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:317:in `factory'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/brew-services.rb:110:in `run!'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/brew-services.rb:578:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/utils.rb:81:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:81:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:108:in `<main>'

```

**Comment by chasinglogic** [comment]
I have opened https://jira.mongodb.org/browse/SERVER-43133 for this.

**Comment by chasinglogic** [comment]
I have pushed a fix for this, please let me know if this resolved your issue. Thanks!

**Comment by ceyhunsony** [comment]
Hi @chasinglogic , thank you for the quick fix! I can confirm the issue is resolved once the formulas got updated using:
```bash
brew tap mongodb/brew
```

**Comment by chasinglogic** [comment]
Sounds good
