### ISSUE TITLE
Tapping results in invalid formula error

### ISSUE THREAD

**Issue by gregnoonan** [mongodb/homebrew-brew#13]
16 hours ago the mongodb package seemed to disappear from the homebrew/core tap. Trying to tap this repo results in invalid formula errors. Here is the full --debug report from tapping this repo:

```
brew tap mongodb/brew --debug                                                                 9:45:02
==> Tapping mongodb/brew
Cloning into '/usr/local/Homebrew/Library/Taps/mongodb/homebrew-brew'...
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 13 (delta 4), reused 3 (delta 0), pack-reused 0
Unpacking objects: 100% (13/13), done.
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/mongodb/homebrew-brew/Formula/mongodb-community.rb
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/mongodb/homebrew-brew/Formula/mongodb-community.rb
execution expired
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/mongodb/homebrew-brew/Formula/mongodb-community@3.6.rb
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/mongodb/homebrew-brew/Formula/mongodb-community@3.6.rb
execution expired
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/mongodb/homebrew-brew/Formula/mongodb-community@3.2.rb
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/mongodb/homebrew-brew/Formula/mongodb-community@3.2.rb
execution expired
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/mongodb/homebrew-brew/Formula/mongodb-community@3.4.rb
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/mongodb/homebrew-brew/Formula/mongodb-community@3.4.rb
execution expired
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/mongodb/homebrew-brew/Formula/mongodb-community@4.0.rb
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/mongodb/homebrew-brew/Formula/mongodb-community@4.0.rb
execution expired
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/mongodb/homebrew-brew/Formula/mongodb-community-shell.rb
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/mongodb/homebrew-brew/Formula/mongodb-community-shell.rb
execution expired
Error: Cannot tap mongodb/brew: invalid syntax in tap!
/usr/local/Homebrew/Library/Homebrew/tap.rb:281:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/tap.rb:56:in `tap'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```
Not sure if I'm doing something wrong or what.

**Comment by chasinglogic** [comment]
Thanks for the report I'm looking at this now

**Comment by chasinglogic** [comment]
This seems related to https://jira.mongodb.org/browse/SERVER-43133

It seems there is a network failure or slowness of some sort causing the Formula to hit an execution time out.

**Comment by chasinglogic** [comment]
I have pushed a fix for the above ticket, can you try adding the tap again and let me know if this resolved this issue? Thanks!

**Comment by chasinglogic** [comment]
I'm closing this issue due to inactivity.
